<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" total="12" passed="8">
  <reporter-output>
  </reporter-output>
  <suite name="JUnitTestForClassPen" duration-ms="48" started-at="2015-11-24T19:47:25Z" finished-at="2015-11-24T19:47:25Z">
    <groups>
    </groups>
    <test name="TestNG tests" duration-ms="48" started-at="2015-11-24T19:47:25Z" finished-at="2015-11-24T19:47:25Z">
      <class name="ClassUnderTest.PenNGTest">
        <test-method status="PASS" signature="testGetColorOnBlue()[pri:0, instance:ClassUnderTest.PenNGTest@75828a0f]" name="testGetColorOnBlue" duration-ms="14" started-at="2015-11-24T22:47:25Z" finished-at="2015-11-24T22:47:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetColorOnBlue -->
        <test-method status="FAIL" signature="testGetColorOnGreen()[pri:0, instance:ClassUnderTest.PenNGTest@75828a0f]" name="testGetColorOnGreen" duration-ms="2" started-at="2015-11-24T22:47:25Z" finished-at="2015-11-24T22:47:25Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [GREEN] but found [BLUE]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [GREEN] but found [BLUE]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at ClassUnderTest.PenNGTest.testGetColorOnGreen(PenNGTest.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetColorOnGreen -->
        <test-method status="PASS" signature="testIsWorkOnNegative()[pri:0, instance:ClassUnderTest.PenNGTest@75828a0f]" name="testIsWorkOnNegative" duration-ms="0" started-at="2015-11-24T22:47:25Z" finished-at="2015-11-24T22:47:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testIsWorkOnNegative -->
        <test-method status="PASS" signature="testIsWorkOnPositive()[pri:0, instance:ClassUnderTest.PenNGTest@75828a0f]" name="testIsWorkOnPositive" duration-ms="0" started-at="2015-11-24T22:47:25Z" finished-at="2015-11-24T22:47:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testIsWorkOnPositive -->
        <test-method status="PASS" signature="testIsWorkOnZero()[pri:0, instance:ClassUnderTest.PenNGTest@75828a0f]" name="testIsWorkOnZero" duration-ms="0" started-at="2015-11-24T22:47:25Z" finished-at="2015-11-24T22:47:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testIsWorkOnZero -->
        <test-method status="PASS" signature="testWriteOnInkEqualToWordLength()[pri:0, instance:ClassUnderTest.PenNGTest@75828a0f]" name="testWriteOnInkEqualToWordLength" duration-ms="1" started-at="2015-11-24T22:47:25Z" finished-at="2015-11-24T22:47:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWriteOnInkEqualToWordLength -->
        <test-method status="PASS" signature="testWriteOnInkMoreThenWordLength()[pri:0, instance:ClassUnderTest.PenNGTest@75828a0f]" name="testWriteOnInkMoreThenWordLength" duration-ms="1" started-at="2015-11-24T22:47:25Z" finished-at="2015-11-24T22:47:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWriteOnInkMoreThenWordLength -->
        <test-method status="PASS" signature="testWriteOnInkLessThenWordLength()[pri:0, instance:ClassUnderTest.PenNGTest@75828a0f]" name="testWriteOnInkLessThenWordLength" duration-ms="0" started-at="2015-11-24T22:47:25Z" finished-at="2015-11-24T22:47:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWriteOnInkLessThenWordLength -->
        <test-method status="PASS" signature="testWriteOnNotWork()[pri:0, instance:ClassUnderTest.PenNGTest@75828a0f]" name="testWriteOnNotWork" duration-ms="0" started-at="2015-11-24T22:47:25Z" finished-at="2015-11-24T22:47:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWriteOnNotWork -->
        <test-method status="FAIL" signature="testWriteOnSizeLetterEqualZero()[pri:0, instance:ClassUnderTest.PenNGTest@75828a0f]" name="testWriteOnSizeLetterEqualZero" duration-ms="1" started-at="2015-11-24T22:47:25Z" finished-at="2015-11-24T22:47:25Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [] but found [testWord]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [] but found [testWord]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at ClassUnderTest.PenNGTest.testWriteOnSizeLetterEqualZero(PenNGTest.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWriteOnSizeLetterEqualZero -->
        <test-method status="FAIL" signature="testWriteOnSizeLetterLessZero()[pri:0, instance:ClassUnderTest.PenNGTest@75828a0f]" name="testWriteOnSizeLetterLessZero" duration-ms="0" started-at="2015-11-24T22:47:25Z" finished-at="2015-11-24T22:47:25Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [] but found [testWord]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [] but found [testWord]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at ClassUnderTest.PenNGTest.testWriteOnSizeLetterLessZero(PenNGTest.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWriteOnSizeLetterLessZero -->
        <test-method status="FAIL" signature="testWriteOnSizeOfWordMoreThanInc()[pri:0, instance:ClassUnderTest.PenNGTest@75828a0f]" name="testWriteOnSizeOfWordMoreThanInc" duration-ms="0" started-at="2015-11-24T22:47:25Z" finished-at="2015-11-24T22:47:25Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [te] but found [test]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [te] but found [test]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at ClassUnderTest.PenNGTest.testWriteOnSizeOfWordMoreThanInc(PenNGTest.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.TestNG.privateMain(TestNG.java:1364)
	at org.testng.TestNG.main(TestNG.java:1333)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testWriteOnSizeOfWordMoreThanInc -->
      </class> <!-- ClassUnderTest.PenNGTest -->
    </test> <!-- TestNG tests -->
  </suite> <!-- JUnitTestForClassPen -->
</testng-results>
